### PR TITLE
styling changes to share and download page

### PR DESCRIPTION
**Pull request by martenson**
ping @nitesh1989 
this is clean version of https://github.com/nitesh1989/galaxy/pull/2

hide myexperiment export as it does not work now
screenshot 2016-04-01 12 02 07

### CODE REVIEW

**Comment by dannon** [comment]
I actually just had a myexperiment export work fine, so let's hold off on disabling it completely.

**Comment by martenson** [comment]
@dannon it "worked" for me just now but only with an empty workflow :)

**Comment by martenson** [comment]
screenshot 2016-04-01 13 10 49

**Comment by martenson** [comment]
alternatively:
screenshot 2016-04-01 13 27 55

**Pull request merged**
